name: landmarks_classification_env
channels:
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - matplotlib
  - scikit-learn
  - tensorflow
  - requests=2.32
  - pylint=3.3.3
  - pandarallel
  - notebook
  - streamlit
  - protobuf=3.20
