name: landmarks_classification_env
channels:
 - defaults
dependencies:
 - python>=3.8
 - pandas
 - matplotlib
 - scikit-learn
 - scikit-image
 - streamlit
 - tensorflow
 - requests=2.32
 - pylint=3.3.3
 - notebook
 - pip
 - pip: 
     - pandarallel==1.6.5