name: landmarks_classification_env
channels:
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - matplotlib
  - scikit-learn
  - requests=2.32
  - pylint=3.3.3
  - protobuf=3.20.3
  - notebook
  - streamlit
  - pip
  - pip: 
     - pandarallel==1.6.5
     - mediapipe==0.10.21
     - tensorflow
