name: landmarks_classification_env
channels:
  - defaults
dependencies:
  - python>=3.8
  - pandas
  - streamlit
  - scikit-image=0.24.0
  - requests=2.32
  - pylint=3.3.3
  - pip
  - pip: 
     - mediapipe==0.10.21
     - setuptools==76.0.0
     - build==1.2.0
     - tensorflow==2.18.0
